### ISSUE TITLE
SceneAccess Login Failed

### ISSUE THREAD

**Issue by wookienz** [zone117x/Jackett#86] opened 2015-07-18 02:58 UTC
Adding SceneAccess fails with no error besides: "Configuration Failed"

Fedora machine

**Comment by zone117x** [comment] 2015-07-18 18:47
I can't trouble shoot this tracker, I'm not a member. It was implemented by @ictibus

**Comment by wookienz** [comment] 2015-07-21 07:28
Where do i find logs?

**Comment by Kayomani** [comment] 2015-07-25 20:07
This should be fixed by upgrading to v0.5. Reopen if its still an issue.

**Comment by florisrobbemont** [comment] 2015-07-25 22:41
This issue if still present with the 0.5 release. Tried running with and without the safecurl switch. Also tried using the root account when running.

**Comment by Kayomani** [comment] 2015-07-25 23:07
Try running  with --tracing and see if anything useful pops up.

**Comment by florisrobbemont** [comment] 2015-07-25 23:09
Already tried that, but nothing usefull. I think it might be something with the actual request, of something in parsing the result from SceneAccess. 

The PirateBay isn't working either (says it can't find any releases), but other trackers are fine.

**Comment by Kayomani** [comment] 2015-07-25 23:16
Try mozroots -sync ?

**Comment by florisrobbemont** [comment] 2015-07-25 23:23
Don't know what that is, I'm running FreeBSD btw (FreeNAS v9) using Mono v4

**Comment by florisrobbemont** [comment] 2015-07-25 23:25
I ran mozroots, but it didn't work

**Comment by Kayomani** [comment] 2015-07-25 23:29
Run with --Tracing and --UseCurlExec and see what command it runs.

Run it manually and see if you get any errors, you'll want to drop the --output parameter.

**Comment by florisrobbemont** [comment] 2015-07-25 23:31
Ok, I'll try that tomorrow and post the results here

**Comment by wookienz** [comment] 2015-07-26 00:57
running under fedora: mono JackettConsole.exe -t- -l -c

output:

>07-26 08:50:47 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose 
07-26 08:50:52 Info   http://192.168.3.18:9117/admin/configure_indexer 
System.Web.Http.Request:   http://192.168.3.18:9117/admin/configure_indexer
07-26 08:50:52 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
{"indexer":"sceneaccess","name":"SceneAccess","config":{"username":"auser","password":"apassword"}}
07-26 08:50:52 Debug POST: http://192.168.3.18:9117/admin/configure_indexer 
07-26 08:50:52 Debug Body: {"indexer":"sceneaccess","name":"SceneAccess","config":{"username":"auser","password":"apassword"}} 
07-26 08:50:52 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
07-26 08:50:52 Info DefaultHttpControllerSelector SelectController Admin 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Admin
07-26 08:50:52 Info HttpControllerDescriptor CreateController  
System.Web.Http.Controllers: HttpControllerDescriptor CreateController 
07-26 08:50:52 Info DefaultHttpControllerActivator Create  
System.Web.Http.Controllers: DefaultHttpControllerActivator Create 
07-26 08:50:52 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
System.Web.Http.Controllers: DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
07-26 08:50:52 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
System.Web.Http.Controllers: HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
07-26 08:50:52 Info AdminController ExecuteAsync  
System.Web.Http.Controllers: AdminController ExecuteAsync 
07-26 08:50:52 Info ApiControllerActionSelector SelectAction  
System.Web.Http.Action: ApiControllerActionSelector SelectAction 
07-26 08:50:52 Info ApiControllerActionSelector SelectAction Selected action 'Configure()' 
System.Web.Http.Action: ApiControllerActionSelector SelectAction Selected action 'Configure()'
07-26 08:50:52 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
07-26 08:50:52 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
07-26 08:50:52 Info HttpActionBinding ExecuteBindingAsync  
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync 
07-26 08:50:52 Info HttpActionBinding ExecuteBindingAsync  
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync 
07-26 08:50:52 Info ApiControllerActionInvoker InvokeActionAsync Action='Configure()' 
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
07-26 08:50:52 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()' 
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
07-26 08:50:52 Debug UnixSafeCurlWebClient:GetString(Url:https://sceneaccess.eu/login) 
07-26 08:50:52 Debug Running curl --url "https://sceneaccess.eu/login" -i  -sS --user-agent "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" --referer "https://sceneaccess.eu/login" --data "username=auser&password=apassword&submit=come+on+in" --output "/tmp/tmp7a821e86.tmp"  
07-26 08:50:53 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
07-26 08:50:53 Info ApiControllerActionInvoker InvokeActionAsync  
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync 
07-26 08:50:53 Info AdminController ExecuteAsync  
System.Web.Http.Controllers: AdminController ExecuteAsync 
{"name":"SceneAccess","result":"error","error":"Invalid response"}
07-26 08:50:53 Debug Response: {"name":"SceneAccess","result":"error","error":"Invalid response"} 
07-26 08:50:53 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
07-26 08:50:53 Info   Content-type='application/json; charset=utf-8', content-length=66 
System.Web.Http.Request:   Content-type='application/json; charset=utf-8', content-length=66
07-26 08:50:53 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose 
07-26 08:50:53 Info AdminController Dispose  
System.Web.Http.Controllers: AdminController Dispose

**Comment by zone117x** [comment] 2015-07-26 01:04
If anyone has an invite to SCC I can help debug the issue.

**Comment by wookienz** [comment] 2015-07-26 01:11
None sorry.

**Comment by florisrobbemont** [comment] 2015-07-26 11:55
When I run the curl command manually, I get the following error:
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

It might have something to do with my curl version (it's 7.43.0), but I don't know how to fix that.

**Comment by florisrobbemont** [comment] 2015-07-26 11:55
Forcing SSLv3 will result in:
curl: (35) error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by Kayomani** [comment] 2015-07-26 14:28
Does appending --tlsv1 onto the command line when calling curl manually help?

**Comment by florisrobbemont** [comment] 2015-07-26 14:44
I've tried that, it's still giving me that same message.

My curl is compiled using OpenSSL 0.9, and I saw there were newer versions that might have better support for these SSL situations.

The problem is that I can't easily compile a new version of curl on top of the existing one. An option to provide the path to curl might be a solution for that.

**Comment by Kayomani** [comment] 2015-07-26 18:11
You should be able to just download them into a directory somewhere and compile them without touching your existing copy.

http://stackoverflow.com/questions/12636536/install-curl-with-openssl

Let us know if compiling against the latest openssl resolves the situation for you.

**Comment by Kayomani** [comment] 2015-07-27 20:53
Could you try placing this file in the same directory as the JackettConsole.exe and let us know if it makes any difference after restarting the app?

https://raw.githubusercontent.com/Sonarr/Sonarr/7eeabd7ca361077743e313f3d787f2244a7d2f7f/src/NzbDrone.Common/CurlSharp.dll.config

**Comment by florisrobbemont** [comment] 2015-07-28 19:50
Doesn't make a difference... I also tried to enable the FreeBSD setting, but that didn't work either...
I can't confirm it actually looks at the config file, because supplying a faulty setting doesn't throw any errors.

**Comment by Kayomani** [comment] 2015-07-30 23:31
After as MASSIVE amount of messing around i've found the issue.  This is the bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1185708

I've successfully tested a fix on my new fedora 21 machine \o/

**Comment by zone117x** [comment] 2015-07-31 00:46
Nice work @Kayomani !

**Comment by wookienz** [comment] 2015-08-02 12:59
Will that be in the next release?

**Comment by Kayomani** [comment] 2015-08-02 13:47
Yes, there is a release candidate in #109 if you'd like to check if it resolves the issue for you.

**Comment by zone117x** [comment] 2015-08-02 22:18
New release with Kayomani's fixes so hopefully this issue is finished.

**Closed by zone117x** 2015-08-02 22:18 UTC
Labels: bug

**Comment by wookienz** [comment] 2015-08-06 02:17
works, thanks.
