### ISSUE TITLE
"Input string was not in a correct format" when using fr_FR formatting

### ISSUE THREAD

**Issue by nicolus** [zone117x/Jackett#64] opened 2015-06-14 15:13 UTC
I'm using Jackett from France with a French version of Windows 8.1, and whenever I tried adding an indexer I got the error message "Input string was not in a correct format" (or actually "Chaine d'entrée dans un format incorrect" ;-) ).
Then I tried changing the number/date formatting to en_US and now it's working. Might be something to look into.

Thanks for the hard work by the way.

**Comment by Kayomani** [comment] 2015-07-19 22:04
Duplicate of #65 which is in the process of being fixed.

**Closed by Kayomani** 2015-07-19 22:04 UTC
Labels: bug
